apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: sxfk2153z-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: sxfk2153z-go 
  name: sxfk2153z-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: sxfk2153z-go 
